spring:
  datasource:
    url: jdbc:mysql://101.200.230.200:3306/wangwang?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: alskdjfhgHE02
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: demo
  mvc:
    static-path-pattern: /**
  mail:
    # 配置SMTP服务器地址
    host: smtp.qq.com
    # 配置端口号465或者25
    port: 587
    # 发送者邮箱（根据自己邮箱填写）
    username: 912948333@qq.com
    #  配置密码，注意是开启POP3/SMTP的授权密码(根据自己的授权密码填写)
    password: RVFAZTNKRFGCBFJE
    default-encoding: UTF-8
    protocol: smtp
    from: 912948333@qq.com
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      cache:
        period: -1
mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.example.demo.entity
server:
  port: 1145
  address: 127.0.0.1
  tomcat:
    max-swallow-size: 100MB

